name: CI

on: [push, pull_request]

jobs:
  code_quality:
    name: Code quality
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - uses: taiki-e/install-action@just

      - name: Install eget
        run: |
          curl -sSL https://github.com/zyedidia/eget/releases/download/v1.3.4/eget-1.3.4-linux_amd64.tar.gz -o /tmp/eget.tar.gz
          tar -xzf /tmp/eget.tar.gz -C /tmp
          # Move to ~/.local/bin
          mkdir -p ~/.local/bin
          mv /tmp/eget-1.3.4-linux_amd64/eget ~/.local/bin/eget
          chmod +x ~/.local/bin/eget
          # Add ~/.local/bin to PATH
          echo 'export PATH="$HOME/.local/bin:$PATH"' >> $GITHUB_ENV
          # Make sure
          ~/.local/bin/eget --version

      - name: Install dependencies with eget
        shell: bash
        run: |
          eget google/yamlfmt --to ~/.local/bin/
          eget Enter-tainer/typstyle --to ~/.local/bin/ --asset typstyle-linux-x64
          eget typst/typst --to ~/.local/bin/

      - name: Show version information
        shell: bash
        run: |
          eget --version
          typstyle --version
          yamlfmt --version

      - run: just check

